### ISSUE TITLE
Toplevel `modules` is a valid folder name

### ISSUE THREAD

**Issue by ignacy** [mdyd-dev/pos-cli#249] opened 2019-07-19 12:23 UTC
## Expected behavior

```
> ls
modules
```

Is a valid directory structure.

## Actual behavior

`PosCli` requires toplevel folder named `app` to be present.

## Steps to reproduce the problem

Try deploying modules with only the modules folder present

## Version

* pos-cli: 3.0.8
* node: all
* os: all

**Comment by Slashek** [comment] 2019-07-22 10:16
duplicate of #244

**Closed by Slashek** 2019-07-22 10:16 UTC
Labels: bug, discussion needed
